server:
  port: 8080

client:
  url: "chrome-extension://*"

broker:
  prefix:
    destination: "/topic"
    handshake: "/ws-handshake"
    private-message: "/topic/private-message"
    group-message: "/topic/group-message"
    application-message: "/app"

spring:
  application:
    name: chatapp

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:chatappdb
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate