server:
  port: 8089

spring:
  application:
    name: authserver

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:authdb
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'

  kafka:
    bootstrap-servers: "localhost:9092"

    # Consumer
    consumer:
#      group-id: "user-events-consumers"
      group-id: ${random.uuid}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.adoumadje.chatapp.core.events

  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
#                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
                - "https://oauth.pstmn.io/v1/callback"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true


logging:
  level:
    org.springframework.security: trace